// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJVVNz2Nl3HI6Iahyo_YSMChtJ0tCnVUc',
    appId: '1:430832646154:web:cc79928c0f467b47f687f3',
    messagingSenderId: '430832646154',
    projectId: 'microplux-anti-theft-app-2026',
    authDomain: 'microplux-anti-theft-app-2026.firebaseapp.com',
    storageBucket: 'microplux-anti-theft-app-2026.firebasestorage.app',
    measurementId: 'G-GESXFFZLG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1Rmv9z5H_FZ73wAN_SfYoSTQGgRvoEYg',
    appId: '1:430832646154:android:c97cae6199ad960bf687f3',
    messagingSenderId: '430832646154',
    projectId: 'microplux-anti-theft-app-2026',
    storageBucket: 'microplux-anti-theft-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdGa6o3k1sZ9b1E1zLtWQM-JCf-9M9HzM',
    appId: '1:430832646154:ios:0e3f9424227b30b5f687f3',
    messagingSenderId: '430832646154',
    projectId: 'microplux-anti-theft-app-2026',
    storageBucket: 'microplux-anti-theft-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.antiTheftApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdGa6o3k1sZ9b1E1zLtWQM-JCf-9M9HzM',
    appId: '1:430832646154:ios:0e3f9424227b30b5f687f3',
    messagingSenderId: '430832646154',
    projectId: 'microplux-anti-theft-app-2026',
    storageBucket: 'microplux-anti-theft-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.antiTheftApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJVVNz2Nl3HI6Iahyo_YSMChtJ0tCnVUc',
    appId: '1:430832646154:web:fd33081c82a4e15ff687f3',
    messagingSenderId: '430832646154',
    projectId: 'microplux-anti-theft-app-2026',
    authDomain: 'microplux-anti-theft-app-2026.firebaseapp.com',
    storageBucket: 'microplux-anti-theft-app-2026.firebasestorage.app',
    measurementId: 'G-59J25P41GK',
  );
}
